### ISSUE TITLE
Import freezes and prevents character sheet from loading

### ISSUE THREAD

**Issue by avagdumortesin** [zarmstrong/herovau.lt-foundry#2]
After updating to Pathfinder 2nd Edition game to 3.5.0, attempting to import existing characters from HeroVau.lt fails. Until the update to 3.5.2, the failure was silent, and would simply prevent you from being able to access any content on the character sheet; the Actor would show the correct name and image, but the character sheet would not change.

After updating to 3.5.2, I receive the following error in the chat log:

> This PC was exported from Foundry v0.8.9 and this game server is running Foundry v9.249.
> 
> This PC was exported from Pathfinder 2nd Edition: 2.15.1.8325 and this game server is running Pathfinder 2nd Edition: 3.5.2.10605.
> 
> There may be compatibility issues.

Looking at the console log, I see the following:

```
TypeError: An error occurred while rendering CharacterSheetPF2e 100: Cannot read properties of undefined (reading 'map')
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3062:18)
    at async CharacterSheetPF2e._render (foundry.js:3764:5)
onError @ foundry.js:316
(anonymous) @ foundry.js:3023
Promise.catch (async)
render @ foundry.js:3021
render @ foundry.js:4259
render @ foundry.js:10776
_onUpdate @ foundry.js:10830
_onUpdate @ foundry.js:13708
_onUpdate @ main.bundle.js:1
_onUpdate @ main.bundle.js:1
callback @ foundry.js:10260
(anonymous) @ foundry.js:10212
_handleUpdateDocuments @ foundry.js:10212
_updateDocuments @ foundry.js:10093
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
update @ document.mjs:456
importFromJSON @ main.bundle.js:1
await in importFromJSON (async)
xmlhttp.onreadystatechange @ herovault-min.js:115
XMLHttpRequest.send (async)
importCharacter @ herovault-min.js:115
xmlhttp.onreadystatechange @ herovault-min.js:115
XMLHttpRequest.send (async)
requestCharacter @ herovault-min.js:115
close @ herovault-min.js:110
close @ foundry.js:43937
submit @ foundry.js:43926
_onClickButton @ foundry.js:43888
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

Is this issue related to #issue #1 ?

**Comment by zarmstrong** [comment]
Can you try the following:

Click the troubleshooting button and hit remigrate (after the actor is imported)
![unknown](https://user-images.githubusercontent.com/565269/156016500-86e7527d-7be9-43fd-a46d-2228b5d71984.png)

**Comment by avagdumortesin** [comment]
Same issue on Forge; the first and second appeared when loading the table, the third after remigrating, and the others when attempting to load the actor.

```
Uncaught (in promise) Error: You may not assign the value of a world-level Setting before the Game is ready.
    at ClientSettings.set (foundry.js:2200:34)
    at new WorldClock (main.bundle.js:1:430521)
    at Object.onSetup (main.bundle.js:1:1440759)
    at main.bundle.js:1:1393673
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5525:11)
    at Game._initializeGameView (foundry.js:6498:16)
    at Game._initializeView (foundry.js:6474:21)
    at Game.initialize (foundry.js:5430:16)
set @ foundry.js:2200
WorldClock @ main.bundle.js:1
onSetup @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
_call @ foundry.js:294
callAll @ foundry.js:253
setupGame @ foundry.js:5525
_initializeGameView @ foundry.js:6498
_initializeView @ foundry.js:6474
initialize @ foundry.js:5430
await in initialize (async)
window.addEventListener.once @ foundry.js:62436
foundry.js:316 
        
       TypeError: An error occurred while rendering CharacterSheetPF2e 99: Cannot read properties of undefined (reading 'map')
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3062:18)
    at async CharacterSheetPF2e._render (foundry.js:3764:5)
onError @ foundry.js:316
(anonymous) @ foundry.js:3023
Promise.catch (async)
render @ foundry.js:3021
render @ foundry.js:4259
_onClickDocumentName @ foundry.js:47362
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:316 
        
       TypeError: An error occurred while rendering CharacterSheetPF2e 99: Cannot read properties of undefined (reading 'map')
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3062:18)
    at async CharacterSheetPF2e._render (foundry.js:3764:5)
onError @ foundry.js:316
(anonymous) @ foundry.js:3023
Promise.catch (async)
render @ foundry.js:3021
render @ foundry.js:4259
render @ foundry.js:10776
_onDeleteEmbeddedDocuments @ foundry.js:10933
_onDeleteEmbeddedDocuments @ foundry.js:13753
_handleDeleteEmbeddedDocuments @ foundry.js:10432
_deleteEmbeddedDocuments @ foundry.js:10335
await in _deleteEmbeddedDocuments (async)
delete @ backend.mjs:214
await in delete (async)
deleteDocuments @ document.mjs:410
deleteDocuments @ main.bundle.js:1
deleteEmbeddedDocuments @ document.mjs:558
deleteEmbeddedDocuments @ main.bundle.js:1
migrateWorldActor @ main.bundle.js:1
await in migrateWorldActor (async)
migrateWorldDocuments @ main.bundle.js:1
await in migrateWorldDocuments (async)
runMigrations @ main.bundle.js:1
runMigration @ main.bundle.js:1
await in runMigration (async)
exports.remigrate @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:316 
        
       TypeError: An error occurred while rendering CharacterSheetPF2e 99: Cannot read properties of undefined (reading 'map')
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3062:18)
    at async CharacterSheetPF2e._render (foundry.js:3764:5)
onError @ foundry.js:316
(anonymous) @ foundry.js:3023
Promise.catch (async)
render @ foundry.js:3021
render @ foundry.js:4259
render @ foundry.js:10776
_onUpdate @ foundry.js:10830
_onUpdate @ foundry.js:13708
_onUpdate @ main.bundle.js:1
_onUpdate @ main.bundle.js:1
callback @ foundry.js:10260
(anonymous) @ foundry.js:10212
_handleUpdateDocuments @ foundry.js:10212
_updateDocuments @ foundry.js:10093
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
migrateWorldDocuments @ main.bundle.js:1
await in migrateWorldDocuments (async)
runMigrations @ main.bundle.js:1
runMigration @ main.bundle.js:1
await in runMigration (async)
exports.remigrate @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:316 
        
       TypeError: An error occurred while rendering CharacterSheetPF2e 99: Cannot read properties of undefined (reading 'map')
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3062:18)
    at async CharacterSheetPF2e._render (foundry.js:3764:5)
onError @ foundry.js:316
(anonymous) @ foundry.js:3023
Promise.catch (async)
render @ foundry.js:3021
render @ foundry.js:4259
render @ foundry.js:10776
_onDeleteEmbeddedDocuments @ foundry.js:10933
_onDeleteEmbeddedDocuments @ foundry.js:13753
_handleDeleteEmbeddedDocuments @ foundry.js:10432
_deleteEmbeddedDocuments @ foundry.js:10335
await in _deleteEmbeddedDocuments (async)
delete @ backend.mjs:214
await in delete (async)
deleteDocuments @ document.mjs:410
deleteDocuments @ main.bundle.js:1
await in deleteDocuments (async)
deleteEmbeddedDocuments @ document.mjs:558
deleteEmbeddedDocuments @ main.bundle.js:1
migrateWorldActor @ main.bundle.js:1
await in migrateWorldActor (async)
migrateWorldDocuments @ main.bundle.js:1
await in migrateWorldDocuments (async)
runMigrations @ main.bundle.js:1
runMigration @ main.bundle.js:1
foundry.js:316 
        
       TypeError: An error occurred while rendering CharacterSheetPF2e 99: Cannot read properties of undefined (reading 'map')
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3062:18)
    at async CharacterSheetPF2e._render (foundry.js:3764:5)
onError @ foundry.js:316
(anonymous) @ foundry.js:3023
Promise.catch (async)
render @ foundry.js:3021
render @ foundry.js:4259
render @ foundry.js:10776
_onUpdate @ foundry.js:10830
_onUpdate @ foundry.js:13708
_onUpdate @ main.bundle.js:1
_onUpdate @ main.bundle.js:1
callback @ foundry.js:10260
(anonymous) @ foundry.js:10212
_handleUpdateDocuments @ foundry.js:10212
_updateDocuments @ foundry.js:10093
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
migrateWorldDocuments @ main.bundle.js:1
await in migrateWorldDocuments (async)
runMigrations @ main.bundle.js:1
runMigration @ main.bundle.js:1
3foundry.js:316 
        
       TypeError: An error occurred while rendering CharacterSheetPF2e 99: Cannot read properties of undefined (reading 'map')
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3062:18)
    at async CharacterSheetPF2e._render (foundry.js:3764:5)
onError @ foundry.js:316
(anonymous) @ foundry.js:3023
Promise.catch (async)
render @ foundry.js:3021
render @ foundry.js:4259
_onClickDocumentName @ foundry.js:47362
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

Following the steps on my local server did allow the character sheet to open.

**Comment by avagdumortesin** [comment]
If it helps, the HeroVau.lt ID of the character I'm using for testing is 2e22b8e1f5a745ff4dc0ea17fb48f3fc.

**Comment by zarmstrong** [comment]
Ok, since the build in migrator doesn't seem to fix it, it's likely that due to the character sheet changes made in the 2e system, that import cannot be converted to the new format. Unfortunately, the best option is to reimport.

**Comment by zarmstrong** [comment]
herovault itself is sheet agnostic and doesn't really mess with the contents of a character sheet.

**Comment by avagdumortesin** [comment]
Sorry, I guess it was lost in my original post: I have deleted and recreated/reimported the actor multiple times. I'm not sure why it's failing to fix on Forge, but works on my local server.

**Comment by avagdumortesin** [comment]
... And now it's working on Forge after restarting my system. Thanks for your help.

**Comment by zarmstrong** [comment]
Super strange!  Thanks for letting me know though. Hopefully it was just something super wonky
